sudo: required
services:
  - docker

before_install:
  - docker build -t mahmedk13/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mahmedk13/react-test npm test
after_success:
  - docker build -t mahmedk13/multi-client ./client
  - docker build -t mahmedk13/multi-nginx ./nginx
  - docker build -t mahmedk13/multi-server ./server
  - docker build -t mahmedk13/multi-worker ./worker
  #login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login --username "DOCKER_ID" --password-stdin
  # take these images and push them to the docker hub
  - docker push mahmedk13/multi-client
  - docker push mahmedk13/multi-nginx
  - docker push mahmedk13/multi-server
  - docker push mahmedk13/multi-worker
